<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_617181aa77521',
		'title' => 'Zillow Builder\'s Information',
		'fields' => array(
			array(
				'key' => 'field_617181bce0fa8',
				'label' => 'Zillow Builder\'s Information',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_617181e1e0fa9',
				'label' => 'Corporate Builder Number',
				'name' => 'corporate_builder_number',
				'type' => 'text',
				'instructions' => 'This is a unique identifier for the parent corporation (e.g. builder headquarters).',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6171824de0fab',
				'label' => 'Corporate State',
				'name' => 'corporate_state',
				'type' => 'text',
				'instructions' => 'A valid 2-character state abbreviation where the parent corporation is incorporated or located in.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61718266e0fac',
				'label' => 'Corporate Name',
				'name' => 'corporate_name',
				'type' => 'text',
				'instructions' => 'This is the name of the corporation.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61718278e0fad',
				'label' => 'Builder Number',
				'name' => 'builder_number',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 5,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6171829de0fae',
				'label' => 'Brand Name',
				'name' => 'brand_name',
				'type' => 'text',
				'instructions' => 'The brand or marketing name that will be displayed to consumers.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_617182bae0faf',
				'label' => 'Brand Logo',
				'name' => 'brand_logo',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_617182d1e0fb0',
				'label' => 'Reporting Name',
				'name' => 'reporting_name',
				'type' => 'text',
				'instructions' => 'Unique name used for reporting and billing purposes.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_617182e9e0fb1',
				'label' => 'Default Leads Email',
				'name' => 'default_leads_email',
				'type' => 'email',
				'instructions' => 'The builder-level default email address for leads.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_61718352e0fb2',
				'label' => 'Builder Website',
				'name' => 'builder_website',
				'type' => 'url',
				'instructions' => 'The URL to the builder’s website.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-zillow',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;