<?php
//if( function_exists('acf_add_local_field_group') ):
//
//	acf_add_local_field_group(array(
//		'key' => 'group_616ce8591de8e',
//		'title' => 'Subdivision',
//		'fields' => array(
//			array(
//				'key' => 'field_616ce86025aca',
//				'label' => 'THE BASICS',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616cec5625ace',
//				'label' => 'Zillow Listing Status',
//				'name' => 'zillow_listing_status',
//				'type' => 'true_false',
//				'instructions' => 'Enable this Subdivision to Zillow',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'message' => '',
//				'default_value' => 1,
//				'ui' => 1,
//				'ui_on_text' => 'Yes',
//				'ui_off_text' => 'No',
//			),
//			array(
//				'key' => 'field_616da5e8f6ff4',
//				'label' => 'Coming Soon Community',
//				'name' => 'coming_soon_community',
//				'type' => 'checkbox',
//				'instructions' => 'Is this a coming soon Community
//If checkboxe is checked, open Resources the resources tab to complete coming soon content.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Yes' => 'Yes',
//				),
//				'allow_custom' => 0,
//				'default_value' => array(
//				),
//				'layout' => 'vertical',
//				'toggle' => 0,
//				'return_format' => 'value',
//				'save_custom' => 0,
//			),
//			array(
//				'key' => 'field_61770ef921daf',
//				'label' => 'Featured Community',
//				'name' => 'featured_community',
//				'type' => 'true_false',
//				'instructions' => 'Checkbox to featured community on the homepage “featured showcase Community” section.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'message' => '',
//				'default_value' => 0,
//				'ui' => 1,
//				'ui_on_text' => 'Yes',
//				'ui_off_text' => 'No',
//			),
//			array(
//				'key' => 'field_616ce88025acb',
//				'label' => 'Community Status',
//				'name' => 'community_status',
//				'type' => 'select',
//				'instructions' => 'A community will only show up as “Coming Soon” if status = ComingSoon and no plans are
//provided for the subdivision. All other values for the status attribute, or not provided, will result in Active communities (as long as at least 1 plan is provided).',
//				'required' => 1,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Active' => 'Active',
//					'Grand Opening' => 'Grand Opening',
//					'Close Out' => 'Close Out',
//					'Coming Soon' => 'Coming Soon',
//				),
//				'default_value' => false,
//				'allow_null' => 0,
//				'multiple' => 0,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'array',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616ce99e25acc',
//				'label' => 'SubdivisionNumber',
//				'name' => 'subdivisionnumber_id',
//				'type' => 'number',
//				'instructions' => 'Number assigned by you for that community. Unique identification number among all of the builder’s subdivisions.',
//				'required' => 1,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => 'sub',
//				'append' => '',
//				'min' => '',
//				'max' => '',
//				'step' => '',
//			),
//			array(
//				'key' => 'field_616ceb1025acd',
//				'label' => 'Community Type',
//				'name' => 'community_type',
//				'type' => 'select',
//				'instructions' => 'Community lifestyle attribute. Set to one of the possible values.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Gated' => 'Gated',
//					'Adult' => 'Adult',
//					'CondoOnly' => 'CondoOnly',
//					'AgeRestricted' => 'AgeRestricted',
//					'Urban' => 'Urban',
//					'Townhomes' => 'Townhomes',
//					'Green' => 'Green',
//				),
//				'default_value' => false,
//				'allow_null' => 0,
//				'multiple' => 0,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'array',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616d9cb897f26',
//				'label' => 'Subdivision Website',
//				'name' => 'subwebsite',
//				'type' => 'url',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616cf08e25ad6',
//				'label' => 'Description',
//				'name' => 'subdescription',
//				'type' => 'textarea',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => '',
//				'new_lines' => 'wpautop',
//			),
//			array(
//				'key' => 'field_616cee0625acf',
//				'label' => 'COMMUNITY LOCATION',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616cee4825ad0',
//				'label' => 'Street',
//				'name' => 'SubStreet1',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616cee5c25ad1',
//				'label' => 'Street 2',
//				'name' => 'SubStreet2',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616cee7225ad2',
//				'label' => 'City',
//				'name' => 'SubCity',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616cef0b25ad3',
//				'label' => 'State',
//				'name' => 'SubState',
//				'type' => 'select',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Alabama' => 'Alabama',
//					'Alaska' => 'Alaska',
//					'Arizona' => 'Arizona',
//					'Arkansas' => 'Arkansas',
//					'California' => 'California',
//					'Colorado' => 'Colorado',
//					'Connecticut' => 'Connecticut',
//					'Delaware' => 'Delaware',
//					'Florida' => 'Florida',
//					'Georgia' => 'Georgia',
//					'Hawaii' => 'Hawaii',
//					'Idaho' => 'Idaho',
//					'IllinoisIndiana' => 'IllinoisIndiana',
//					'Iowa' => 'Iowa',
//					'Kansas' => 'Kansas',
//					'Kentucky' => 'Kentucky',
//					'Louisiana' => 'Louisiana',
//					'Maine' => 'Maine',
//					'Maryland' => 'Maryland',
//					'Massachusetts' => 'Massachusetts',
//					'Michigan' => 'Michigan',
//					'Minnesota' => 'Minnesota',
//					'Mississippi' => 'Mississippi',
//					'Missouri' => 'Missouri',
//					'MontanaNebraska' => 'MontanaNebraska',
//					'Nevada' => 'Nevada',
//					'New Hampshire' => 'New Hampshire',
//					'New Jersey' => 'New Jersey',
//					'New Mexico' => 'New Mexico',
//					'New York' => 'New York',
//					'North Carolina' => 'North Carolina',
//					'North Dakota' => 'North Dakota',
//					'Ohio' => 'Ohio',
//					'Oklahoma' => 'Oklahoma',
//					'Oregon' => 'Oregon',
//					'PennsylvaniaRhode Island' => 'PennsylvaniaRhode Island',
//					'South Carolina' => 'South Carolina',
//					'South Dakota' => 'South Dakota',
//					'Tennessee' => 'Tennessee',
//					'Texas' => 'Texas',
//					'Utah' => 'Utah',
//					'Vermont' => 'Vermont',
//					'Virginia' => 'Virginia',
//					'Washington' => 'Washington',
//					'West Virginia' => 'West Virginia',
//					'Wisconsin' => 'Wisconsin',
//					'Wyoming' => 'Wyoming',
//				),
//				'default_value' => false,
//				'allow_null' => 0,
//				'multiple' => 0,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'value',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616d7d06fc276',
//				'label' => 'Zip Code',
//				'name' => 'subzip',
//				'type' => 'number',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'min' => 5,
//				'max' => 5,
//				'step' => '',
//			),
//			array(
//				'key' => 'field_616cef4025ad4',
//				'label' => 'Phone Number',
//				'name' => 'phone_number',
//				'type' => 'number',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'min' => '',
//				'max' => '',
//				'step' => '',
//			),
//			array(
//				'key' => 'field_616cef8e25ad5',
//				'label' => 'Google Map',
//				'name' => 'google_map',
//				'type' => 'google_map',
//				'instructions' => 'Enter subdivision address to auto generat the latitude and longitude.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'center_lat' => '',
//				'center_lng' => '',
//				'zoom' => '',
//				'height' => '',
//			),
//			array(
//				'key' => 'field_616d74a50fc90',
//				'label' => 'SALES OFFICE',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616d74c70fc91',
//				'label' => 'Out of Subdivision?',
//				'name' => 'out_of_subdivision',
//				'type' => 'checkbox',
//				'instructions' => 'Is the Subdivision sales office located outside of the community?
//Specifies if the sales office is outside the community. If it is, <SubAddress> is required.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Yes' => 'Yes',
//				),
//				'allow_custom' => 0,
//				'default_value' => array(
//				),
//				'layout' => 'vertical',
//				'toggle' => 0,
//				'return_format' => 'value',
//				'save_custom' => 0,
//			),
//			array(
//				'key' => 'field_616d75c70fc92',
//				'label' => 'Street',
//				'name' => 'street_address_1',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616d77b6d97ff',
//				'label' => 'Street',
//				'name' => 'street_address_2',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616d77efd9800',
//				'label' => 'City',
//				'name' => 'city',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616d7808d9801',
//				'label' => 'State',
//				'name' => 'state',
//				'type' => 'select',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Alabama' => 'Alabama',
//					'Alaska' => 'Alaska',
//					'Arizona' => 'Arizona',
//					'Arkansas' => 'Arkansas',
//					'California' => 'California',
//					'Colorado' => 'Colorado',
//					'Connecticut' => 'Connecticut',
//					'Delaware' => 'Delaware',
//					'Florida' => 'Florida',
//					'Georgia' => 'Georgia',
//					'Hawaii' => 'Hawaii',
//					'Idaho' => 'Idaho',
//					'IllinoisIndiana' => 'IllinoisIndiana',
//					'Iowa' => 'Iowa',
//					'Kansas' => 'Kansas',
//					'Kentucky' => 'Kentucky',
//					'Louisiana' => 'Louisiana',
//					'Maine' => 'Maine',
//					'Maryland' => 'Maryland',
//					'Massachusetts' => 'Massachusetts',
//					'Michigan' => 'Michigan',
//					'Minnesota' => 'Minnesota',
//					'Mississippi' => 'Mississippi',
//					'Missouri' => 'Missouri',
//					'MontanaNebraska' => 'MontanaNebraska',
//					'Nevada' => 'Nevada',
//					'New Hampshire' => 'New Hampshire',
//					'New Jersey' => 'New Jersey',
//					'New Mexico' => 'New Mexico',
//					'New York' => 'New York',
//					'North Carolina' => 'North Carolina',
//					'North Dakota' => 'North Dakota',
//					'Ohio' => 'Ohio',
//					'Oklahoma' => 'Oklahoma',
//					'Oregon' => 'Oregon',
//					'PennsylvaniaRhode Island' => 'PennsylvaniaRhode Island',
//					'South Carolina' => 'South Carolina',
//					'South Dakota' => 'South Dakota',
//					'Tennessee' => 'Tennessee',
//					'Texas' => 'Texas',
//					'Utah' => 'Utah',
//					'Vermont' => 'Vermont',
//					'Virginia' => 'Virginia',
//					'Washington' => 'Washington',
//					'West Virginia' => 'West Virginia',
//					'Wisconsin' => 'Wisconsin',
//					'Wyoming' => 'Wyoming',
//				),
//				'default_value' => false,
//				'allow_null' => 0,
//				'multiple' => 0,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'value',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616d783cd9802',
//				'label' => 'Zipcode',
//				'name' => 'zipcode',
//				'type' => 'number',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'min' => 5,
//				'max' => 5,
//				'step' => '',
//			),
//			array(
//				'key' => 'field_616d7878d9803',
//				'label' => 'Google Map',
//				'name' => 'google_map',
//				'type' => 'google_map',
//				'instructions' => 'Enter subdivision address to auto generat the latitude and longitude.',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'center_lat' => '',
//				'center_lng' => '',
//				'zoom' => '',
//				'height' => '',
//			),
//			array(
//				'key' => 'field_616d78a9d9804',
//				'label' => 'Phone Number',
//				'name' => 'sales_office_phone_number',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616d74c70fc91',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616d8600b3d6a',
//				'label' => 'SCHOOL & DISTRICTS',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616d863bb3d6b',
//				'label' => 'School District',
//				'name' => 'school_district',
//				'type' => 'taxonomy',
//				'instructions' => 'If a school district or school is not supplied in the dropdowns below	<a href="/wp-admin/edit-tags.php?taxonomy=schools&post_type=communities">Click here</a> to add additional school districts and schools. You will need to update this page to populate new options in the dropdown.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'schools',
//				'field_type' => 'select',
//				'allow_null' => 0,
//				'add_term' => 0,
//				'save_terms' => 0,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_616d86beb3d6c',
//				'label' => 'Elementary School',
//				'name' => 'school_elementary',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'schools',
//				'field_type' => 'select',
//				'allow_null' => 0,
//				'add_term' => 0,
//				'save_terms' => 0,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_616d9850b3d6d',
//				'label' => 'Middle School',
//				'name' => 'middle_school',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'schools',
//				'field_type' => 'select',
//				'allow_null' => 0,
//				'add_term' => 0,
//				'save_terms' => 1,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_616d9878b3d6e',
//				'label' => 'High School',
//				'name' => 'high_school',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'schools',
//				'field_type' => 'select',
//				'allow_null' => 0,
//				'add_term' => 0,
//				'save_terms' => 1,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_616d995197f1a',
//				'label' => 'PHOTOS & VIDEOS',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616d996e97f1b',
//				'label' => 'Featured Image',
//				'name' => 'featured_image',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'id',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_616d999c97f1c',
//				'label' => 'Gallery',
//				'name' => 'gallery',
//				'type' => 'gallery',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//				'preview_size' => 'medium',
//				'insert' => 'append',
//				'library' => 'all',
//				'min' => '',
//				'max' => '',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_616d99f197f1d',
//				'label' => 'Community Logo',
//				'name' => 'community_logo',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_616d9a2397f1e',
//				'label' => 'Video',
//				'name' => 'video_community',
//				'type' => 'oembed',
//				'instructions' => 'Add a Youtube video URL',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'width' => '',
//				'height' => '',
//			),
//			array(
//				'key' => 'field_616d9bcc97f20',
//				'label' => 'Virtual Tour',
//				'name' => 'virtual_tour',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'block',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_616d9be197f21',
//						'label' => 'Virtual Tour Url',
//						'name' => 'virtual_tour_url',
//						'type' => 'url',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//					),
//					array(
//						'key' => 'field_616d9c0e97f22',
//						'label' => 'Virtual Tour Cover Image',
//						'name' => 'virtual_tour_cover_image',
//						'type' => 'image',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'array',
//						'preview_size' => 'medium',
//						'library' => 'all',
//						'min_width' => '',
//						'min_height' => '',
//						'min_size' => '',
//						'max_width' => '',
//						'max_height' => '',
//						'max_size' => '',
//						'mime_types' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_616da07ebf822',
//				'label' => 'Community Lot Map',
//				'name' => 'community_lot_map',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'block',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_616da08abf823',
//						'label' => 'Community Lot Map Image',
//						'name' => 'community_lot_map_image',
//						'type' => 'image',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'array',
//						'preview_size' => 'medium',
//						'library' => 'all',
//						'min_width' => '',
//						'min_height' => '',
//						'min_size' => '',
//						'max_width' => '',
//						'max_height' => '',
//						'max_size' => '',
//						'mime_types' => '',
//					),
//					array(
//						'key' => 'field_616da09ebf824',
//						'label' => 'Community Lot Map URL',
//						'name' => 'community_lot_map_url',
//						'type' => 'url',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_616d9d3397f27',
//				'label' => 'AMENITIES & SERVICES',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616d9d5d97f28',
//				'label' => 'Amenities',
//				'name' => 'subamenity',
//				'type' => 'select',
//				'instructions' => 'Indicate whether an amenity exists. This element can be used multiple times, once for each amenity.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Basketball' => 'Basketball',
//					'Baseball' => 'Baseball',
//					'Volleyball' => 'Volleyball',
//					'Soccer' => 'Soccer',
//					'Tennis' => 'Tennis',
//					'GolfCourse' => 'GolfCourse',
//					'Playground' => 'Playground',
//					'Pool' => 'Pool',
//					'Views' => 'Views',
//					'Lake' => 'Lake',
//					'Pond' => 'Pond',
//					'Beach' => 'Beach',
//					'MarinaWaterfrontLots' => 'MarinaWaterfrontLots',
//					'Park' => 'Park',
//					'Trails' => 'Trails',
//					'Greenbelt' => 'Greenbelt',
//					'Clubhouse' => 'Clubhouse',
//					'CommunityCenter' => 'CommunityCenter',
//				),
//				'default_value' => array(
//				),
//				'allow_null' => 0,
//				'multiple' => 1,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'value',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616da162bf828',
//				'label' => 'Community Open Amenities',
//				'name' => 'community_open_amenities',
//				'type' => 'select',
//				'instructions' => 'A description of a subdivision amenity. Multiple elements are allowed.',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'HealthAndFitness' => 'HealthAndFitness',
//					'CommunityServices' => 'CommunityServices',
//					'SocialActivities' => 'SocialActivities',
//					'Education' => 'Education',
//					'LocalAreaAmenities' => 'LocalAreaAmenities',
//					'Custom' => 'Custom',
//				),
//				'default_value' => array(
//				),
//				'allow_null' => 0,
//				'multiple' => 1,
//				'ui' => 1,
//				'ajax' => 0,
//				'return_format' => 'value',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616da1b0bf829',
//				'label' => 'Open Amenties Name',
//				'name' => 'open_amenties_name',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da162bf828',
//							'operator' => '==',
//							'value' => 'Custom',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616d9f47bf81d',
//				'label' => 'Services',
//				'name' => 'services',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'block',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_616d9f64bf81e',
//						'label' => 'Service Type',
//						'name' => 'service_type',
//						'type' => 'select',
//						'instructions' => 'Services that are “included” or required with home ownership.',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'HOA' => 'HOA',
//							'GroundsCare' => 'GroundsCare',
//							'Security' => 'Security',
//							'Maintenance' => 'Maintenance',
//							'MedicalCare' => 'MedicalCare',
//							'Shopping' => 'Shopping',
//						),
//						'default_value' => false,
//						'allow_null' => 0,
//						'multiple' => 0,
//						'ui' => 1,
//						'ajax' => 1,
//						'return_format' => 'value',
//						'placeholder' => '',
//					),
//					array(
//						'key' => 'field_616d9f8bbf81f',
//						'label' => 'Service Name',
//						'name' => 'service_name',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 1,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_616d9f64bf81e',
//									'operator' => '!=empty',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_616d9fb9bf820',
//						'label' => 'Monthly Fee',
//						'name' => 'monthly_fee',
//						'type' => 'number',
//						'instructions' => 'If the service is paid monthly, the monthly cost. If there is a service element, either the monthly or yearly fee information is required. If <YearlyFee> is also provided, <MonthlyFee> will be used.',
//						'required' => 1,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_616d9f64bf81e',
//									'operator' => '!=empty',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'min' => '',
//						'max' => '',
//						'step' => '',
//					),
//					array(
//						'key' => 'field_616da00fbf821',
//						'label' => 'Yearly Fee',
//						'name' => 'yearly_fee',
//						'type' => 'number',
//						'instructions' => 'If the service is paid yearly, the yearly cost. If there is a service element, either the monthly or yearly fee information is required. If <MonthlyFee> is also provided, <MonthlyFee> will be used instead.',
//						'required' => 0,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_616d9f64bf81e',
//									'operator' => '!=empty',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'min' => '',
//						'max' => '',
//						'step' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_616da0b2bf825',
//				'label' => 'RELATIONSHIPS',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616da0ccbf826',
//				'label' => 'Community Floorplans',
//				'name' => 'community_floorplans',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'floorplan',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//					1 => 'post_type',
//				),
//				'elements' => array(
//					0 => 'featured_image',
//				),
//				'min' => '',
//				'max' => '',
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_616da112bf827',
//				'label' => 'Community Homes',
//				'name' => 'community_homes',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'homes',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//					1 => 'post_type',
//				),
//				'elements' => array(
//					0 => 'featured_image',
//				),
//				'min' => '',
//				'max' => '',
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_616da20abf82a',
//				'label' => 'PROMOTION',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616da240bf82b',
//				'label' => 'Promotion Type',
//				'name' => 'promotion_type',
//				'type' => 'select',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'Consumer' => 'Consumer',
//					'Agent' => 'Agent',
//				),
//				'default_value' => false,
//				'allow_null' => 0,
//				'multiple' => 0,
//				'ui' => 1,
//				'ajax' => 1,
//				'return_format' => 'value',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_616da26cbf82c',
//				'label' => 'Promo Headline',
//				'name' => 'promo_headline',
//				'type' => 'text',
//				'instructions' => 'Short description of the promotion.',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da240bf82b',
//							'operator' => '!=empty',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_616da29abf82d',
//				'label' => 'Promo Description',
//				'name' => 'promo_description',
//				'type' => 'textarea',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da240bf82b',
//							'operator' => '!=empty',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => '',
//				'new_lines' => 'wpautop',
//			),
//			array(
//				'key' => 'field_616da2b5bf82e',
//				'label' => 'Start Date',
//				'name' => 'start_date',
//				'type' => 'date_picker',
//				'instructions' => 'The promotion start date.',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da240bf82b',
//							'operator' => '!=empty',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'display_format' => 'd/m/Y',
//				'return_format' => 'YYY-mm-dd',
//				'first_day' => 1,
//			),
//			array(
//				'key' => 'field_616da2f5bf82f',
//				'label' => 'End Date',
//				'name' => 'end_date',
//				'type' => 'date_picker',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da240bf82b',
//							'operator' => '!=empty',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'display_format' => 'd/m/Y',
//				'return_format' => 'YYY-mm-dd',
//				'first_day' => 1,
//			),
//			array(
//				'key' => 'field_616da31dbf830',
//				'label' => 'FEATURES & UPGRADES',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'left',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_616da345bf831',
//				'label' => 'Community Brochure',
//				'name' => 'community_brochure',
//				'type' => 'link',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//			),
//			array(
//				'key' => 'field_616da641f6ff5',
//				'label' => 'Coming Soon Content Area',
//				'name' => 'coming_soon_content_area',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_616da5e8f6ff4',
//							'operator' => '==',
//							'value' => 'Yes',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'block',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_616da66cf6ff6',
//						'label' => 'Coming Soon Headline',
//						'name' => 'coming_soon_headline',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => 'COMING SOON!',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_616da6c4f6ff7',
//						'label' => 'Coming Soon Announcements',
//						'name' => 'coming_soon_announcements',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => 'Be the first to know. Sign-Up for VIP updates and announcements.',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_616da709f6ff8',
//						'label' => 'Coming Soon Contact Form',
//						'name' => 'coming_soon_contact_form',
//						'type' => 'wysiwyg',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'tabs' => 'all',
//						'toolbar' => 'basic',
//						'media_upload' => 1,
//						'delay' => 0,
//					),
//					array(
//						'key' => 'field_616da738f6ff9',
//						'label' => 'Anticipated Sales Opening',
//						'name' => 'anticipated_sales_opening',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => 'Summer 2022',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_61770cd6b1356',
//				'label' => 'Smart Features',
//				'name' => 'smart_features',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'features',
//				'field_type' => 'multi_select',
//				'allow_null' => 0,
//				'add_term' => 1,
//				'save_terms' => 1,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_61770d12b1357',
//				'label' => 'New Features',
//				'name' => 'new_features',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'features',
//				'field_type' => 'multi_select',
//				'allow_null' => 0,
//				'add_term' => 1,
//				'save_terms' => 1,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//			array(
//				'key' => 'field_61770d31b1358',
//				'label' => 'Healthy Features',
//				'name' => 'healthy_features',
//				'type' => 'taxonomy',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'taxonomy' => 'features',
//				'field_type' => 'multi_select',
//				'allow_null' => 0,
//				'add_term' => 1,
//				'save_terms' => 1,
//				'load_terms' => 1,
//				'return_format' => 'object',
//				'multiple' => 0,
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'communities',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'acf_after_title',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => array(
//			0 => 'the_content',
//			1 => 'excerpt',
//			2 => 'discussion',
//			3 => 'comments',
//			4 => 'revisions',
//			5 => 'author',
//			6 => 'format',
//			7 => 'featured_image',
//			8 => 'categories',
//			9 => 'tags',
//			10 => 'send-trackbacks',
//		),
//		'active' => true,
//		'description' => '',
//	));
//
//endif;