<?php
/**
 * Template Name: Smart Home Tech
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site may use a
 * different template.
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
 *
 * @package New_Home_Inc
 */

get_header();
?>

    <main id="primary" class="site-main">
		<?php  get_template_part( 'template-parts/components/global/banner/banner-dynamic-title');  ?>
		<?php get_template_part( 'template-parts/components/navigations/smart-tech');  ?>
		<?php while ( have_posts() ) : the_post(); ?>
			<?php get_template_part( 'template-parts/content', 'smart-home' ); ?>


            <map name="image-map">
                <area target="_top" alt="This is a test" title="This is a test" href="" coords="1192,1250,1278" shape="circle">
                <area target="" alt="window" title="window" href="" coords="429,1109,NaN" shape="circle">
            </map>

            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="http://newhomeinc.test/wp-content/uploads/2022/01/1-e1642170874957.png" usemap="#image-map">

            <map name="image-map">
                <area target="_self" alt="test" title="test" href="" coords="" shape="rect">
            </map>
		<?php endwhile; // End of the loop.?>
    </main><!-- #main -->

<?php
get_footer();
